# -*- coding: utf-8 -*-
"""AnalyticsVisualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbZg70wXlTF3i5FZpcQYssMcCR1OHFvC

## Metric 1 : Avg_Time_Success
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

uploaded = files.upload()
df_time = pd.read_csv("Analytics_Elemental_final - AvgTime_Success.csv")
df_time

def plot_avg_time_success(df):
    import matplotlib.pyplot as plt
    import numpy as np

    bg_color = "#f5e9d4"    # outer background
    ax_color = "#fdf8f0"    # plot background

    bar_color  = "#1f77b4"  # deep blue
    edge_color = "#4b4038"  # warm brown

    df_plot = df.copy()
    levels = df_plot["level_id"].tolist()
    avg_time = df_plot["avg_time_success_s"].values

    x = np.arange(len(levels))

    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor(bg_color)
    ax.set_facecolor(ax_color)

    bars = ax.bar(
        x,
        avg_time,
        width=0.45,
        color=bar_color,
        edgecolor=edge_color,
        linewidth=1.2
    )

    max_val = avg_time.max()
    ax.set_ylim(0, max_val * 1.25)

    for xi, bar in enumerate(bars):
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width()/2,
            height + max_val * 0.03,
            f"{height:.1f}s",
            ha="center",
            va="bottom",
            fontsize=12,
            color=edge_color,
            weight="bold"
        )

    ax.set_title(
        "Average Time per Level (Success)",
        fontsize=22,
        weight="bold",
        color=edge_color,
        pad=20
    )
    ax.set_xlabel("Level", fontsize=15, color=edge_color)
    ax.set_ylabel("Average Time (s)", fontsize=15, color=edge_color)

    ax.set_xticks(x)
    ax.set_xticklabels(levels, fontsize=12, color=edge_color)
    ax.tick_params(axis="y", labelcolor=edge_color, labelsize=12)

    ax.grid(
        axis="y",
        linestyle=":",
        linewidth=1,
        alpha=0.5,
        color="#b8a996"
    )

    plt.tight_layout()
    plt.show()

plot_avg_time_success(df_time)

def plot_survival_curve(df):
    import numpy as np
    import matplotlib.pyplot as plt

    
    bg_color = "#f5e9d4"
    ax_color = "#fdf8f0"
    line_color = "#1f77b4"
    edge_color = "#4b4038"

    df_plot = df.copy()

    
    levels = df_plot["level_id"].tolist()
    starts = df_plot["starts"].values

    # Survival = players who reached this level / players who started Level 1
    baseline = starts[0]    
    survival = starts / baseline

    x = np.arange(len(levels))

    # --- Figure ---
    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor(bg_color)
    ax.set_facecolor(ax_color)

    # --- Line plot ---
    ax.plot(
        x,
        survival,
        marker="o",
        linewidth=2.5,
        markersize=8,
        color=line_color,
        markerfacecolor="white",
        markeredgecolor=line_color,
        markeredgewidth=2
    )

    # --- Label each point with % ---
    for xi, yi in zip(x, survival):
        ax.text(
            xi,
            yi + 0.03,
            f"{yi*100:.1f}%",
            ha="center",
            va="bottom",
            fontsize=12,
            color=edge_color,
            weight="bold"
        )

    ax.set_ylim(0, 1.10)  

    # --- Titles, Labels ---
    ax.set_title(
        "Player Survival Curve Across Levels",
        fontsize=22,
        weight="bold",
        color=edge_color,
        pad=20
    )

    ax.set_xlabel("Level", fontsize=15, color=edge_color)
    ax.set_ylabel("Survival Rate (%)", fontsize=15, color=edge_color)

    ax.set_xticks(x)
    ax.set_xticklabels(levels, fontsize=12, color=edge_color)
    ax.tick_params(axis="y", labelcolor=edge_color, labelsize=12)

    ax.grid(
        axis="y",
        linestyle=":",
        linewidth=1,
        alpha=0.5,
        color="#b8a996"
    )

    plt.tight_layout()
    plt.show()

plot_survival_curve(df_funnel)

"""## Metric 2 : Level Completion Funnel"""

uploaded = files.upload()
csv_name = list(uploaded.keys())[0]
df_funnel = pd.read_csv(csv_name)
df_funnel

def plot_level_funnel_horizontal(df):
    import matplotlib.pyplot as plt
    import numpy as np

    bg_color = "#f5e9d4"         
    ax_color = "#fdf8f0"        

    dark_blue  = "#1f77b4"       
    orange     = "#ff9933"       
    edge_color = "#4b4038"       

    df_plot = df.copy()
    levels = df_plot["level_id"].tolist()

    starts = df_plot["starts"].values
    completes = df_plot["completions"].values

    y = np.arange(len(levels))
    bar_height = 0.35

    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor(bg_color)
    ax.set_facecolor(ax_color)

    bars1 = ax.barh(
        y - bar_height/2,
        starts,
        height=bar_height,
        label="Starts",
        color=dark_blue,
        edgecolor=edge_color,
        linewidth=1.2
    )

    bars2 = ax.barh(
        y + bar_height/2,
        completes,
        height=bar_height,
        label="Completions",
        color=orange,
        edgecolor=edge_color,
        linewidth=1.2
    )

    max_val = max(starts.max(), completes.max())
    ax.set_xlim(0, max_val * 1.25)

    def label_bars(bars):
        for bar in bars:
            width = bar.get_width()
            ax.text(
                width + max_val * 0.02,
                bar.get_y() + bar.get_height()/2,
                str(int(width)),
                va="center",
                fontsize=12,
                color=edge_color,
                weight="bold"
            )

    label_bars(bars1)
    label_bars(bars2)

    ax.set_title(
        "Level Funnel: Started vs Completed",
        fontsize=22,
        weight="bold",
        color=edge_color,
        pad=20
    )

    ax.set_xlabel("Players", fontsize=15, color=edge_color)
    ax.set_ylabel("Level", fontsize=15, color=edge_color)

    ax.set_yticks(y)
    ax.set_yticklabels(levels, fontsize=12, color=edge_color)
    ax.tick_params(axis="x", labelcolor=edge_color, labelsize=12)

    ax.grid(
        axis="x",
        linestyle=":",
        linewidth=1,
        alpha=0.5,
        color="#b8a996"
    )

    legend = ax.legend(
        frameon=True,
        facecolor="#f2e7d6",
        edgecolor="#b8a996",
        fontsize=12
    )
    for text in legend.get_texts():
        text.set_color("black")

    plt.tight_layout()
    plt.show()

plot_level_funnel_horizontal(df_funnel)

def plot_avg_attempts_line(df):
    bg_color = "#f5e9d4"    
    ax_color = "#fdf8f0"    
    line_color = "#6aa7f7"  

    df_plot = df.copy()
    df_plot = df_plot.dropna(subset=["avg_attempts_per_completion"])

    levels = df_plot["level_id"].tolist()
    avg_attempts = df_plot["avg_attempts_per_completion"].values

    x = range(len(levels))

    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor(bg_color)
    ax.set_facecolor(ax_color)
    
    ax.plot(
        x,
        avg_attempts,
        marker="o",
        linestyle="-",
        linewidth=2.5,
        markersize=8,
        color=line_color,
        markerfacecolor="white",
        markeredgecolor=line_color,
        markeredgewidth=2,
    )

    max_val = max(avg_attempts)
    ax.set_ylim(0, max_val * 1.25)

    for xi, yi in zip(x, avg_attempts):
        ax.text(
            xi,
            yi + max_val * 0.04,
            f"{yi:.2f}",
            ha="center",
            va="bottom",
            fontsize=11,
            color="#4e4a45",
            weight="bold",
        )

    ax.set_title(
        "Avg Attempts per Completed Level",
        fontsize=22,
        weight="bold",
        color="#5a5047",
        pad=20,
    )
    ax.set_xlabel("Level", fontsize=15, color="#5a5047")
    ax.set_ylabel("Attempts", fontsize=15, color="#5a5047")

    ax.set_xticks(list(x))
    ax.set_xticklabels(levels, rotation=0, fontsize=12, color="#4e4a45")
    ax.tick_params(axis="y", labelcolor="#4e4a45", labelsize=12)

    ax.grid(
        axis="y",
        linestyle=":",
        linewidth=1,
        alpha=0.6,
        color="#c8b9a6",
    )

    plt.tight_layout()
    plt.show()

plot_avg_attempts_line(df_funnel)

"""## Metric 3 : HeartLoss Graphs"""

uploaded = files.upload()
csv_name = list(uploaded.keys())[0]
df_loss = pd.read_csv(csv_name)

df_loss.head()

df_loss["cause"] = df_loss["cause"].astype(str).str.strip()

invalid_causes = ["Unknown", "", "ssswwsw"]

df_loss = df_loss[~df_loss["cause"].isin(invalid_causes)]

print("Unique causes:", df_loss["cause"].unique())
print("Unique levels:", df_loss["level_id"].unique())

"""## Bar Graphs"""

def plot_heart_loss_bar(df, level_name):
    import matplotlib.pyplot as plt

    bg_color = "#f5e9d4"    
    ax_color = "#fdf8f0"    

    
    level_df = df[df["level_id"] == level_name].copy()
    if level_df.empty:
        print(f"No data for {level_name}")
        return

    level_df["cause"] = level_df["cause"].astype(str).str.strip()
    level_df = level_df[~level_df["cause"].isin(["Unknown", "", "nan"])]

    if level_df.empty:
        print(f"No valid causes for {level_name} after cleaning")
        return

    
    grouped = level_df.groupby("cause").size().sort_values(ascending=False)

    
    cause_colors = {
        "FireWall":    "#f7c8c8",  
        "IceWall":     "#a3c9f9",  
        "PlayerTouch": "#d7c4f3",  
        "Enemy":       "#f7e6a3",  
    }
    
    default_color = "#b6e3c6"      

    colors = [cause_colors.get(c, default_color) for c in grouped.index]

   
    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor(bg_color)
    ax.set_facecolor(ax_color)

    
    bars = ax.bar(
        grouped.index,
        grouped.values,
        width=0.45,
        color=colors,
        edgecolor="#7a6f64",   
        linewidth=1.0
    )

   
    max_val = grouped.max()
    ax.set_ylim(0, max_val * 1.25)

    
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width()/2,
            height + max_val * 0.04,
            str(int(height)),
            ha='center',
            va='bottom',
            fontsize=13,
            color="#4e4a45",
            weight="bold"
        )

    
    ax.set_title(
        f"Heart Losses by Cause — {level_name}",
        fontsize=22,
        weight="bold",
        color="#5a5047",
        pad=20
    )

   
    ax.set_xlabel("Cause", fontsize=15, color="#5a5047")
    ax.set_ylabel("Heart Loss Count", fontsize=15, color="#5a5047")
    ax.grid(
        axis="y",
        linestyle=":",
        linewidth=1,
        alpha=0.6,
        color="#c8b9a6"
    )
    ax.tick_params(axis='x', labelcolor="#4e4a45", labelsize=12)
    ax.tick_params(axis='y', labelcolor="#4e4a45", labelsize=12)

    plt.tight_layout()
    plt.show()

levels = df_loss["level_id"].unique().tolist()
levels

plot_heart_loss_bar(df_loss, levels[1])

plot_heart_loss_bar(df_loss, levels[0])

plot_heart_loss_bar(df_loss, levels[2])

plot_heart_loss_bar(df_loss, levels[3])

plot_heart_loss_bar(df_loss, levels[4])

"""## Heatmaps"""

# Visualisation functions
def upload_csv():
    """Upload CSV in Colab and return dataframe with fail_count=1 column."""
    uploaded = files.upload()
    csv_name = list(uploaded.keys())[0]
    print("Using CSV:", csv_name)

    df = pd.read_csv(csv_name)
    df["fail_count"] = 1
    return df


def prepare_level(df, level_name):
    """Filter a level and compute tile_x, tile_y, fail_count."""
    level = df[df["level_id"] == level_name].copy()
    print(f"Rows for {level_name} :", len(level))

    x_offset = level["grid_x"].min()
    y_offset = level["grid_y"].min()
    print("Offsets:", x_offset, y_offset)

    level["tile_x"] = level["grid_x"] - x_offset
    level["tile_y"] = level["grid_y"] - y_offset
    level["fail_count"] = 1

    return level


def compute_grid(layout):
    n_rows = len(layout)
    n_cols = len(layout[0])
    return n_rows, n_cols


def build_ascii_scatter(level, layout, size_scale=200):
    """Compute row/col + sizes/colors for ASCII heatmap scatter."""
    n_rows, n_cols = compute_grid(layout)

    rows = []
    cols = []
    sizes = []
    colors = []

    for _, row in level.iterrows():
        tx = int(row["tile_x"])
        ty = int(row["tile_y"])
        r = n_rows - 1 - ty
        c = tx

        if 0 <= r < n_rows and 0 <= c < n_cols:
            rows.append(r)
            cols.append(c)
            sizes.append(row["fail_count"] * size_scale)
            colors.append(row["fail_count"])

    return rows, cols, sizes, colors, n_rows, n_cols


def plot_ascii(layout, rows, cols, sizes, colors,
               n_rows, n_cols, title, cbar_label):
    """Draw ASCII maze with scatter overlay (same styling as original)."""
    plt.figure(figsize=(8, 4))

    plt.imshow(np.zeros((n_rows, n_cols)), cmap="gray_r", origin="upper")
    for r in range(n_rows):
        for c in range(n_cols):
            ch = layout[r][c]
            if ch != "#":
                plt.text(
                    c, r, ch,
                    ha="center", va="center",
                    color="white", fontsize=8, fontweight="bold"
                )

    sc = plt.scatter(cols, rows, s=sizes, c=colors, alpha=0.7)
    plt.colorbar(sc, label=cbar_label)
    plt.title(title)
    plt.xticks(range(n_cols))
    plt.yticks(range(n_rows))
    plt.gca().invert_yaxis()
    plt.tight_layout()
    plt.show()


def upload_level_image():
    """Upload a PNG for a level and return the image array."""
    uploaded_img = files.upload()
    img_name = list(uploaded_img.keys())[0]
    print("Using image:", img_name)

    img = plt.imread(img_name)
    return img


def build_image_scatter(level, layout, img,
                        grid_left_frac, grid_right_frac,
                        grid_bottom_frac, grid_top_frac,
                        size_scale=300):
    """
    Map tile coordinates to image pixel positions using the same fraction logic
    as your original code.
    """
    h, w = img.shape[:2]

    GRID_LEFT   = grid_left_frac * w
    GRID_RIGHT  = grid_right_frac * w
    GRID_BOTTOM = grid_bottom_frac * h
    GRID_TOP    = grid_top_frac * h

    n_rows, n_cols = compute_grid(layout)

    xs, ys, sizes, labels = [], [], [], []

    for _, row in level.iterrows():
        tx = int(row["tile_x"])
        ty = int(row["tile_y"])

        r = n_rows - 1 - ty
        c = tx

        if 0 <= r < n_rows and 0 <= c < n_cols:
            x_img = GRID_LEFT + (c + 0.5) / n_cols * (GRID_RIGHT - GRID_LEFT)
            y_img = GRID_TOP  - (r + 0.5) / n_rows * (GRID_TOP - GRID_BOTTOM)

            xs.append(x_img)
            ys.append(y_img)
            sizes.append(row["fail_count"] * size_scale)
            labels.append(int(row["fail_count"]))

    return xs, ys, sizes, labels


def plot_image_overlay(img, xs, ys, sizes, labels, title):
    """Draw maze PNG with bubble overlay (same style as original)."""
    plt.figure(figsize=(10, 4))
    plt.imshow(img)

    plt.scatter(xs, ys, s=sizes, alpha=0.7, edgecolors="black")

    for x, y, lbl in zip(xs, ys, labels):
        plt.text(x, y, lbl,
                 ha="center", va="center",
                 color="white", fontsize=10)

    plt.axis("off")
    plt.title(title)
    plt.show()


def build_tile_heatmap(level, layout):
    """
    Aggregate fail_count per tile into a 2D grid aligned with the ASCII layout.
    """
    n_rows, n_cols = compute_grid(layout)
    grid = np.zeros((n_rows, n_cols), dtype=int)

    for _, row in level.iterrows():
        tx = int(row["tile_x"])
        ty = int(row["tile_y"])
        r = n_rows - 1 - ty
        c = tx

        if 0 <= r < n_rows and 0 <= c < n_cols:
            grid[r, c] += int(row["fail_count"])

    return grid, n_rows, n_cols


def plot_tile_heatmap(layout, grid, n_rows, n_cols, title):
    """
    Show a tile heatmap (colored squares) with ASCII characters on top.
    """
    plt.figure(figsize=(10, 4))

    # heatmap of fail counts
    im = plt.imshow(
        grid,
        cmap="hot",        
        origin="upper",
        vmin=0,
        vmax=max(1, grid.max())
    )

    # overlay ASCII characters
    for r in range(n_rows):
        for c in range(n_cols):
            ch = layout[r][c]
            if ch != "#":
                plt.text(
                    c, r, ch,
                    ha="center", va="center",
                    color="white", fontsize=8, fontweight="bold"
                )

    cbar = plt.colorbar(im)
    cbar.set_label("Fail Count")

    plt.title(title)
    plt.xticks(range(n_cols))
    plt.yticks(range(n_rows))
    plt.gca().invert_yaxis()
    plt.tight_layout()
    plt.show()

df_heartloss = upload_csv()
df_heartloss.head()

"""## Level 1"""

# Level 1 – ASCII scatter

LEVEL1_NAME = "Level1Scene"

layout1 = [
    "###################",
    "#F........H......E#",
    "###.######.########",
    "###.######.########",
    "###.##...#.########",
    "###I##...#.########",
    "###.##...#I########",
    "#W.........########",
    "###################"
]

level1 = prepare_level(df_heartloss, LEVEL1_NAME)

rows1, cols1, sizes1, colors1, n_rows1, n_cols1 = build_ascii_scatter(
    level1, layout1, size_scale=200
)

plot_ascii(
    layout1,
    rows1, cols1, sizes1, colors1,
    n_rows1, n_cols1,
    title="Level 1 – failure scatter on ASCII layout\n(player positions, not exact hazard tiles)",
    cbar_label="fail_count (per logged cell)"
)

# Level 1 tile heatmap

grid1, n_rows1_hm, n_cols1_hm = build_tile_heatmap(level1, layout1)

plot_tile_heatmap(
    layout1,
    grid1,
    n_rows1_hm,
    n_cols1_hm,
    title="Level 1 – tile fail heatmap"
)

# Upload Level 1 image

img1 = upload_level_image()

# Level 1 – scatter overlay on maze PNG

xs1_img, ys1_img, sizes1_img, labels1_img = build_image_scatter(
    level1, layout1, img1,
    grid_left_frac=0.06,
    grid_right_frac=0.94,
    grid_bottom_frac=0.12,
    grid_top_frac=0.88,
    size_scale=300
)

plot_image_overlay(
    img1, xs1_img, ys1_img, sizes1_img, labels1_img,
    title=f"{LEVEL1_NAME} – failure scatter over maze art"
)

"""## Level 2"""

# Level 2 – ASCII scatter

LEVEL2_NAME = "Level2Scene"

layout2 = [

    "###########################",
    "#F........##############.W#",
    "#.###.###I##############..#",
    "#...#.#.........I....H....#",
    "###.#.######H##########.###",
    "#.#.#.#.#.#..##########.###",
    "#.#.###.I...###########.###",
    "#.#.....#........H..I....##",
    "#.########H################",
    "#..I..H.....#########....##",
    "#.###################.....#",
    "#.........................#",
    "#.........................#",
    "#.........................#",
    "#.1111..2222..1111..2222.E#",
    "###########################"
]

level2 = prepare_level(df_heartloss, LEVEL2_NAME)

rows2, cols2, sizes2, colors2, n_rows2, n_cols2 = build_ascii_scatter(
    level2, layout2, size_scale=200
)

plot_ascii(
    layout2,
    rows2, cols2, sizes2, colors2,
    n_rows2, n_cols2,
    title="Level 2 – failure scatter on ASCII layout\n(player positions, not exact hazard tiles)",
    cbar_label="fail_count (per logged cell)"
)

# Level 2 tile heatmap

grid2, n_rows2_hm, n_cols2_hm = build_tile_heatmap(level2, layout2)

plot_tile_heatmap(
    layout2,
    grid2,
    n_rows2_hm,
    n_cols2_hm,
    title="Level 2 – tile fail heatmap"
)

# Upload Level 2 image

img2 = upload_level_image()

# Level 2 – scatter overlay on maze PNG

xs2_img, ys2_img, sizes2_img, labels2_img = build_image_scatter(
    level2, layout2, img2,
    grid_left_frac=0.06,
    grid_right_frac=0.94,
    grid_bottom_frac=0.12,
    grid_top_frac=0.88,
    size_scale=300
)

plot_image_overlay(
    img2, xs2_img, ys2_img, sizes2_img, labels2_img,
    title=f"{LEVEL2_NAME} – failure scatter over maze art"
)

"""## Level 3"""

# Level 3 – ASCII scatter

LEVEL3_NAME = "Level3Scene"

layout3 = [
    "#########################",
    "##...#.#.#.............##",
    "##...#.#.#.#.#.#.#.#....#",
    "#....#...#.#.#.#.#.#...##",
    "##.....#...#.#.#.#.#.#.##",
    "##...#.#.#.#.#.#.#.#...##",
    "##.#.#.###.#...#.#.#...F#",
    "#W...#...#.#.#.#.#.#...##",
    "#....#.#.#.#.#.#.#.#...##",
    "##...#.#.#.#.#...#.#...##",
    "##222#.#.....#.#...#111##",
    "#########################"
]

level3 = prepare_level(df_heartloss, LEVEL3_NAME)

rows3, cols3, sizes3, colors3, n_rows3, n_cols3 = build_ascii_scatter(
    level3, layout3, size_scale=200
)

plot_ascii(
    layout3,
    rows3, cols3, sizes3, colors3,
    n_rows3, n_cols3,
    title=f"{LEVEL3_NAME} – failure scatter on ASCII",
    cbar_label="fail_count"
)


grid3, n_rows3_hm, n_cols3_hm = build_tile_heatmap(level3, layout3)

plot_tile_heatmap(
    layout3,
    grid3,
    n_rows3_hm,
    n_cols3_hm,
    title="Level 3 – tile fail heatmap"
)

# Upload Level 3 image

img3 = upload_level_image()

# Level 3 – scatter overlay on maze PNG

xs3_img, ys3_img, sizes3_img, labels3_img = build_image_scatter(
    level3, layout3, img3,
    grid_left_frac=0.08,
    grid_right_frac=0.94,
    grid_bottom_frac=0.12,
    grid_top_frac=0.88,
    size_scale=300
)

plot_image_overlay(
    img3, xs3_img, ys3_img, sizes3_img, labels3_img,
    title=f"{LEVEL3_NAME} – failure scatter over maze"
)

"""## Level 4"""

# Level 4 – ASCII scatter

LEVEL4_NAME = "Level4Scene"

layout4 = [
    "################################",
    "#F##.............3#............#",
    "#.##.#####.####.###.######.###L#",
    "#...........4##..M..######...#L#",
    "##.#Z############.##########.#L#",
    "#P.#Z###...######.##.....#...#.#",
    "####.###.#.######.##.#.#.#.#.#.#",
    "####.....#.####...##.#.#.#.#.#.#",
    "#W...#.###.####.####.#.#.#.#.#.#",
    "##########......###..........#.#",
    "###################.##########.#",
    "#################M..##########.#",
    "#..################...########.#",
    "#E......###########.#.########.#",
    "#######.LLL#####....#..........#",
    "##########.......#####.#######.#",
    "################################"
]

level4 = prepare_level(df_heartloss, LEVEL4_NAME)

rows4, cols4, sizes4, colors4, n_rows4, n_cols4 = build_ascii_scatter(
    level4, layout4, size_scale=200
)

plot_ascii(
    layout4,
    rows4, cols4, sizes4, colors4,
    n_rows4, n_cols4,
    title=f"{LEVEL4_NAME} – failure scatter on ASCII",
    cbar_label="fail_count"
)


grid4, n_rows4_hm, n_cols4_hm = build_tile_heatmap(level4, layout4)

plot_tile_heatmap(
    layout4,
    grid4,
    n_rows4_hm,
    n_cols4_hm,
    title="Level 4 – tile fail heatmap (corrected)"
)

# Upload Level 4 image

img4 = upload_level_image()

# Level 4 – scatter overlay on maze PNG

xs4_img, ys4_img, sizes4_img, labels4_img = build_image_scatter(
    level4, layout4, img4,
    grid_left_frac=0.08,
    grid_right_frac=0.94,
    grid_bottom_frac=0.12,
    grid_top_frac=0.88,
    size_scale=300
)

plot_image_overlay(
    img4, xs4_img, ys4_img, sizes4_img, labels4_img,
    title=f"{LEVEL4_NAME} – failure scatter over maze"
)

"""## Level5

"""

# Level 5 – ASCII scatter

LEVEL5_NAME = "Level5Scene"

layout5 = [
    "##################",
    "#f..I.4###f..wF.S#",
    "#Iw##fF###FI######",
    "#.I##Fw###.w.Ff.4#",
    "#..II..FMI..######",
    "#F#II#I###..Iw.Ff#",
    "#.#w.#f###.#######",
    "#W#11#....1#######",
    "######LLLLL#######",
    "######LLLLL#######",
    "#######.E.########",
    "##################"
]

level5 = prepare_level(df_heartloss, LEVEL5_NAME)

rows5, cols5, sizes5, colors5, n_rows5, n_cols5 = build_ascii_scatter(
    level5, layout5, size_scale=200
)

plot_ascii(
    layout5,
    rows5, cols5, sizes5, colors5,
    n_rows5, n_cols5,
    title=f"{LEVEL5_NAME} – failure scatter on ASCII",
    cbar_label="fail_count"
)

grid5, n_rows5_hm, n_cols5_hm = build_tile_heatmap(level5, layout5)

plot_tile_heatmap(
    layout5,
    grid5,
    n_rows5_hm,
    n_cols5_hm,
    title="Level 5 – tile fail heatmap (corrected)"
)

# Upload Level 5 image

img5 = upload_level_image()

# Level 5 – scatter overlay on maze PNG

xs5_img, ys5_img, sizes5_img, labels5_img = build_image_scatter(
    level5, layout5, img5,
    grid_left_frac=0.08,
    grid_right_frac=0.94,
    grid_bottom_frac=0.12,
    grid_top_frac=0.88,
    size_scale=300
)

plot_image_overlay(
    img5, xs5_img, ys5_img, sizes5_img, labels5_img,
    title=f"{LEVEL5_NAME} – failure scatter over maze"
)

"""## Metric 4 : Token Completion Rate"""

uploaded = files.upload()
fname = list(uploaded.keys())[0]
df_raw = pd.read_csv(fname)

df = df_raw.copy()

cols = ["level_id", "token_completion_rate", "time_spent_s"]
df = df[cols].dropna()

df["token_completion_rate"] = (
    df["token_completion_rate"].astype(str).str.replace("%", "").astype(float)
)

df["time_spent_s"] = pd.to_numeric(df["time_spent_s"], errors="coerce")
df = df.dropna(subset=["time_spent_s"])

def plot_scatter_subplots(df):
    bg = "#f5e9d4"        
    axbg = "#fdf8f0"      
    point_color = "#6aaed6"  
    outline = "#4b4038"      
    grid_color = "#c8b9a6"

    levels = df["level_id"].unique()
    levels = sorted(levels)   # Keep order: Level1Scene → Level5Scene

    fig, axes = plt.subplots(1, 5, figsize=(26, 5), sharey=True)
    fig.patch.set_facecolor(bg)

    for ax, level in zip(axes, levels):
        sub = df[df["level_id"] == level]

        ax.set_facecolor(axbg)

        ax.scatter(
            sub["time_spent_s"],
            sub["token_completion_rate"],
            s=120,
            alpha=0.85,
            color=point_color,
            edgecolors=outline,
            linewidth=1.0
        )

        ax.set_title(
            level,
            fontsize=16,
            weight="bold",
            color=outline,
            pad=10
        )

        ax.grid(axis="both", linestyle=":", color=grid_color, linewidth=1, alpha=0.7)
        ax.tick_params(axis="both", labelsize=11, labelcolor=outline)

        ax.set_xlabel("Time (s)", fontsize=12, color=outline)

    axes[0].set_ylabel("Token Completion (%)", fontsize=14, color=outline)

    plt.tight_layout()
    plt.show()

plot_scatter_subplots(df)

df_summary = (
    df_tokens.groupby("level_id", as_index=False)
    .agg(
        avg_completion=("token_completion_rate", "mean"),
        attempt_count=("session_id", "nunique") 
    )
)

df_summary

def plot_token_completion_bar(df_summary):
    bg = "#f5e9d4"        
    axbg = "#fdf8f0"      
    bar_color = "#a3c9f9" 
    outline = "#4b4038"   

    fig, ax = plt.subplots(figsize=(12, 7))
    fig.patch.set_facecolor(bg)
    ax.set_facecolor(axbg)
    
    bars = ax.bar(
        df_summary["level_id"],
        df_summary["avg_completion"],
        color=bar_color,
        edgecolor=outline,
        linewidth=1.4,
        width=0.55
    )

    max_val = df_summary["avg_completion"].max()
    ax.set_ylim(0, max(100, max_val * 1.2))

    for bar, val in zip(bars, df_summary["avg_completion"]):
        ax.text(
            bar.get_x() + bar.get_width()/2,
            val + 2,
            f"{val:.0f}%",
            ha="center",
            fontsize=13,
            color=outline,
            weight="bold"
        )

    ax.set_title(
        "Average Token Completion Rate per Level",
        fontsize=22,
        weight="bold",
        color=outline,
        pad=20
    )
    ax.set_xlabel("Level", fontsize=15, color=outline)
    ax.set_ylabel("Completion Rate (%)", fontsize=15, color=outline)

    ax.grid(axis="y", linestyle=":", color="#c8b9a6", linewidth=1.1, alpha=0.7)
    ax.tick_params(axis="x", labelrotation=0, labelsize=12, labelcolor=outline)
    ax.tick_params(axis="y", labelsize=12, labelcolor=outline)

    plt.tight_layout()
    plt.show()

plot_token_completion_bar(df_summary)